### ISSUE TITLE
Can't reduce preview canvas width after going 100%+

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3976] opened 2024-08-20 20:12 UTC
1. Set browser to full screen (makes it easier to grab the canvas handle instead of the browser)
2. Preview
3. Drag width past full screen so cursor wraps around
4. Release drag
5. Try reducing width, can't 

https://github.com/user-attachments/assets/616d2cc7-3255-459b-9485-3219f866ca1e

**Comment by kof** [comment] 2024-08-20 20:24
Is it possible that you were trying to grab outside the screen? its 5 px space you need to catch. I tried, it worked for me

**Comment by johnsicili** [comment] 2024-08-20 20:27
It looks like it sometimes works and sometimes doesn't. The blue bars on both sides of the canvas highlight, so it's the canvas that I'm dragging, pretty sure. There aren't dragging cursors for the window when it's fullscreen

**Comment by kof** [comment] 2024-08-20 20:29
I can even see it staying blue while the cursor is already over to the browser edge and grabbing browser resizable edge

**Comment by johnsicili** [comment] 2024-08-20 20:30
Here's it half working

https://github.com/user-attachments/assets/a6024297-be0c-4dd7-b5a7-728b1890fc9a

**Comment by johnsicili** [comment] 2024-08-20 20:31
And here is another website. As you can see no drag handles 

https://github.com/user-attachments/assets/f554b2fe-5d09-4300-a95c-e23e29cd3ce1

**Comment by kof** [comment] 2024-08-20 20:33
Weirdly not reproducible for me. Try restarting the browser pls

**Comment by kof** [comment] 2024-08-20 20:33
btw can you also check if there are errors in the console when that happens?

**Comment by johnsicili** [comment] 2024-08-20 20:39
Found the issue. If you click too far right it wont drag. Restarted and no chrome exts

https://github.com/user-attachments/assets/9b4a69bc-5b4d-4268-9380-9460214b26ef

**Comment by kof** [comment] 2024-08-20 20:45
I can't repro it but it might have to do with the system/resolution/browser/cursor ... I feel like we don't see the events anymore because cursor is outside while the cursor/hover effect is still there, the cursor is pretty fat for resize and this is a matter of a few px, so there is not enough precision to tell visually

**Comment by kof** [comment] 2024-08-20 20:51
closing for now, will look into that if someone else has this weird prob

**Closed by kof** 2024-08-20 20:51 UTC
Labels: type:bug, area:canvas, prio:1
