### ISSUE TITLE
Color control

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#1843] opened 2023-06-23 18:31 UTC
- [ ] The input with color swatch does not have the correct spacing around the swatch (too much left padding)
- [ ] Color swatch should show the "open" state when the color picker is open.

Prod:
(swatch has uneven appearance of padding)
<img width="137" alt="Screenshot 2023-06-23 at 11 30 27 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/8b46b416-002c-4c10-96ef-ed7bea61502a">

(no open state)
<img width="261" alt="Screenshot 2023-06-23 at 11 33 07 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/9a5abd6a-6856-4dc9-bab6-354136bff851">

<img width="311" alt="Screenshot 2023-06-23 at 11 29 40 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/2123caab-f880-4a83-8917-f32973a5ffc9">

Design:
(padding around the swatch is consistent)
<img width="315" alt="Screenshot 2023-06-23 at 11 32 08 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/a7d60193-81cc-43d6-bc08-3f18063fc445">

<img width="464" alt="Screenshot 2023-06-23 at 11 31 13 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/3f164f19-39ac-41fa-a5ac-059f2db79bae">

(open state of the swatch component)
<img width="183" alt="Screenshot 2023-06-23 at 11 35 48 AM" src="https://github.com/webstudio-is/webstudio-builder/assets/86495896/fa147c89-b35f-4e79-9992-b532eaf4470d">

Figma component: https://www.figma.com/file/sfCE7iLS0k25qCxiifQNLE/%F0%9F%93%9A-Webstudio-Library?type=design&node-id=4%3A3378&t=N1E9gl5gEc6NOqP1-1

**Comment by kof** [comment] 2024-04-14 15:58
duplicate of https://github.com/webstudio-is/webstudio/issues/1244

**Closed by kof** 2024-04-14 15:58 UTC
Labels: type:bug, area:design system, prio:2
