### ISSUE TITLE
Add display: none shortcut to Nav items

### ISSUE THREAD

**Issue by taylornowotny** [webstudio-is/webstudio#2519] opened 2023-10-23 18:35 UTC
This was designed last year but not implemented. We recently had feedback from a user who wants this, so I think now would be a good time to finally build it.

Please read the design carefully, there are many details that I've considered.

<img width="358" alt="Screenshot 2023-10-23 at 11 34 14 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/72db3682-59b9-44c8-a361-cb4212365a53">

Quick summary:
- small toggle button shows when nav item is hovered
- toggling makes the instance display: none
- toggling off returns instance to previous display value (flex, inline, etc)
- changes are synced between this button and style panel
- when an item is hidden it has a different appearance and the button is always visible (see design)
<img width="321" alt="Screenshot 2023-10-23 at 11 33 47 AM" src="https://github.com/webstudio-is/webstudio/assets/86495896/acde3e39-d39f-4344-bc13-24fa36d81e9c">

https://www.figma.com/file/xCBegXEWxROLqA1Y31z2Xo/%F0%9F%93%96-Webstudio-Design-Docs?type=design&node-id=239%3A21865&mode=design&t=CvBDli3HNPh0jxPY-1

**Comment by TrySound** [comment] 2024-01-27 06:08
Duplicate of https://github.com/webstudio-is/webstudio/issues/237

**Closed** 2024-07-21 18:05 UTC
Labels: type:feat, prio:2
