### ISSUE TITLE
Set canonical link

### ISSUE THREAD

**Issue by johnsicili** [webstudio-is/webstudio#3501] opened 2024-06-05 14:48 UTC
As a user, I want Google to know which page is my primary when duplicate content arises.

Currently, when query params are present, they cause duplicate content.... The same content is available at two different URLs. While Google is smart about this, it's best practice to inform them which one you consider the primary page.

Canonical can go in [multiple places](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#comparison-of-canonicalization-methods), but the `head` is the best and users don't have a way to modify the head on a page-level basis except by adding custom meta key-value pairs.

My suggestion is this:
1. I think it makes sense for Webstudio to output a self-referencing canonical for each page. E.g., `/about` auto outputs `/about` as canonical. That way, if `/about?hello=world` is visited, Google will be instructed to use `/about` as the primary page.
2. The user needs to override the default in some cases like pagination. `/posts?page=1` should have a canonical of `/posts?page=1` *not* the default `/posts`. 

Options for how users add it:
1. Custom head HTML on pages
2. Add canonical field to pages with a default value of the current page path
3. Add something similar to custom meta but for custom link, idk what else this would be used for though.

**Comment by pnull** [comment] 2024-11-01 22:00
Possible duplicate of #[#3321](https://github.com/webstudio-is/webstudio/issues/3321)

**Closed** 2024-11-05 16:52 UTC
Labels: type:feat, prio:2, area:seo
